/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTradeRouteImport } from './routes/_authenticated/trade'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCandleTradeRouteImport } from './routes/_authenticated/candle-trade'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedWalletWithdrawRouteImport } from './routes/_authenticated/wallet.withdraw'
import { Route as AuthenticatedWalletDepositRouteImport } from './routes/_authenticated/wallet.deposit'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin/withdrawals'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTradesRouteImport } from './routes/_authenticated/admin/trades'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPlatformSettingsRouteImport } from './routes/_authenticated/admin/platform-settings'
import { Route as AuthenticatedAdminPaymentConfigRouteImport } from './routes/_authenticated/admin/payment-config'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin/overview'
import { Route as AuthenticatedAdminDepositsRouteImport } from './routes/_authenticated/admin/deposits'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin/campaigns'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAssetsRouteImport } from './routes/_authenticated/admin/assets'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradeRoute = AuthenticatedTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandleTradeRoute =
  AuthenticatedCandleTradeRouteImport.update({
    id: '/candle-trade',
    path: '/candle-trade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletWithdrawRoute =
  AuthenticatedWalletWithdrawRouteImport.update({
    id: '/withdraw',
    path: '/withdraw',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletDepositRoute =
  AuthenticatedWalletDepositRouteImport.update({
    id: '/deposit',
    path: '/deposit',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTradesRoute =
  AuthenticatedAdminTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformSettingsRoute =
  AuthenticatedAdminPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentConfigRoute =
  AuthenticatedAdminPaymentConfigRouteImport.update({
    id: '/payment-config',
    path: '/payment-config',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDepositsRoute =
  AuthenticatedAdminDepositsRouteImport.update({
    id: '/deposits',
    path: '/deposits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAssetsRoute =
  AuthenticatedAdminAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/alerts': typeof AuthenticatedAlertsRoute
  '/candle-trade': typeof AuthenticatedCandleTradeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/payment-config': typeof AuthenticatedAdminPaymentConfigRoute
  '/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/alerts': typeof AuthenticatedAlertsRoute
  '/candle-trade': typeof AuthenticatedCandleTradeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/payment-config': typeof AuthenticatedAdminPaymentConfigRoute
  '/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/candle-trade': typeof AuthenticatedCandleTradeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trade': typeof AuthenticatedTradeRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/deposits': typeof AuthenticatedAdminDepositsRoute
  '/_authenticated/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/admin/payment-config': typeof AuthenticatedAdminPaymentConfigRoute
  '/_authenticated/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/wallet/deposit': typeof AuthenticatedWalletDepositRoute
  '/_authenticated/wallet/withdraw': typeof AuthenticatedWalletWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/alerts'
    | '/candle-trade'
    | '/dashboard'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/support'
    | '/trade'
    | '/wallet'
    | '/admin/announcements'
    | '/admin/assets'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/deposits'
    | '/admin/overview'
    | '/admin/payment-config'
    | '/admin/platform-settings'
    | '/admin/reports'
    | '/admin/tickets'
    | '/admin/trades'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/wallet/deposit'
    | '/wallet/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/alerts'
    | '/candle-trade'
    | '/dashboard'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/support'
    | '/trade'
    | '/wallet'
    | '/admin/announcements'
    | '/admin/assets'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/deposits'
    | '/admin/overview'
    | '/admin/payment-config'
    | '/admin/platform-settings'
    | '/admin/reports'
    | '/admin/tickets'
    | '/admin/trades'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/wallet/deposit'
    | '/wallet/withdraw'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/alerts'
    | '/_authenticated/candle-trade'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/trade'
    | '/_authenticated/wallet'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/assets'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/deposits'
    | '/_authenticated/admin/overview'
    | '/_authenticated/admin/payment-config'
    | '/_authenticated/admin/platform-settings'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/trades'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/wallet/deposit'
    | '/_authenticated/wallet/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trade': {
      id: '/_authenticated/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candle-trade': {
      id: '/_authenticated/candle-trade'
      path: '/candle-trade'
      fullPath: '/candle-trade'
      preLoaderRoute: typeof AuthenticatedCandleTradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/withdraw': {
      id: '/_authenticated/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof AuthenticatedWalletWithdrawRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/deposit': {
      id: '/_authenticated/wallet/deposit'
      path: '/deposit'
      fullPath: '/wallet/deposit'
      preLoaderRoute: typeof AuthenticatedWalletDepositRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trades': {
      id: '/_authenticated/admin/trades'
      path: '/trades'
      fullPath: '/admin/trades'
      preLoaderRoute: typeof AuthenticatedAdminTradesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platform-settings': {
      id: '/_authenticated/admin/platform-settings'
      path: '/platform-settings'
      fullPath: '/admin/platform-settings'
      preLoaderRoute: typeof AuthenticatedAdminPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payment-config': {
      id: '/_authenticated/admin/payment-config'
      path: '/payment-config'
      fullPath: '/admin/payment-config'
      preLoaderRoute: typeof AuthenticatedAdminPaymentConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/overview': {
      id: '/_authenticated/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/deposits': {
      id: '/_authenticated/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AuthenticatedAdminDepositsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/assets': {
      id: '/_authenticated/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AuthenticatedAdminAssetsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminAssetsRoute: typeof AuthenticatedAdminAssetsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminDepositsRoute: typeof AuthenticatedAdminDepositsRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedAdminPaymentConfigRoute: typeof AuthenticatedAdminPaymentConfigRoute
  AuthenticatedAdminPlatformSettingsRoute: typeof AuthenticatedAdminPlatformSettingsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminTradesRoute: typeof AuthenticatedAdminTradesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminAssetsRoute: AuthenticatedAdminAssetsRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
    AuthenticatedAdminDepositsRoute: AuthenticatedAdminDepositsRoute,
    AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
    AuthenticatedAdminPaymentConfigRoute: AuthenticatedAdminPaymentConfigRoute,
    AuthenticatedAdminPlatformSettingsRoute:
      AuthenticatedAdminPlatformSettingsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
    AuthenticatedAdminTradesRoute: AuthenticatedAdminTradesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedWalletRouteChildren {
  AuthenticatedWalletDepositRoute: typeof AuthenticatedWalletDepositRoute
  AuthenticatedWalletWithdrawRoute: typeof AuthenticatedWalletWithdrawRoute
}

const AuthenticatedWalletRouteChildren: AuthenticatedWalletRouteChildren = {
  AuthenticatedWalletDepositRoute: AuthenticatedWalletDepositRoute,
  AuthenticatedWalletWithdrawRoute: AuthenticatedWalletWithdrawRoute,
}

const AuthenticatedWalletRouteWithChildren =
  AuthenticatedWalletRoute._addFileChildren(AuthenticatedWalletRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedCandleTradeRoute: typeof AuthenticatedCandleTradeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTradeRoute: typeof AuthenticatedTradeRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedCandleTradeRoute: AuthenticatedCandleTradeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTradeRoute: AuthenticatedTradeRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
